apiVersion: v1
kind: ConfigMap
metadata:
  name: licitaciones-app-config
  namespace: licitaciones
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  POSTGRES_DB: "licitaciones"
  POSTGRES_HOST: "licitaciones-postgres.licitaciones.svc.cluster.local"
  POSTGRES_PORT: "5432"
